### ISSUE TITLE
help wanted

### ISSUE THREAD

**Issue by SAMATHASAMA** [rodrigozambranavargas/DFIG-model-matlab-simulink#1]
Excuse me, which document did you refer to for your simulation? I would appreciate it if provided.Best wishes!

**Comment by rodrigozambranavargas** [comment]
Hi Samathasama the bibliography used are the following:

- Power Electronics for Renewable Energy Systems, Transportation and Industrial Applications (Wiley - IEEE)  Haitham Abu-Rub (Author), Mariusz Malinowski  (Author), Kamal Al-Haddad  (Author)

- Doubly Fed Induction Machine: Modeling and Control for Wind Energy Generation  (ISBN: 978-0-470-76865-5)

**Comment by SAMATHASAMA** [comment]
> Hi Samathasama the bibliography used are the following:
> 
> * Power Electronics for Renewable Energy Systems, Transportation and Industrial Applications (Wiley - IEEE)  Haitham Abu-Rub (Author), Mariusz Malinowski  (Author), Kamal Al-Haddad  (Author)
> * Doubly Fed Induction Machine: Modeling and Control for Wind Energy Generation  (ISBN: 978-0-470-76865-5)

Forgive me as a beginner. After reading the two books you recommended, I did not find the meaning of "REG" in the "Cancelation of cc" on the RSC side. If possible, I would like to trouble you for advice.

**Comment by rodrigozambranavargas** [comment]
Hello Samthasama, the term "REG" refers to the control regulator, for example PID (Proportional Integral Differential) or in my case just PI. The following link may be useful to you (Implementation and Control of a DFIM in Matlab-Simulink)

https://www.youtube.com/watch?v=ddHO1D6_FAw&t=15s

If you have any questions, please let me know.
